### ISSUE TITLE
Setup Backend Project

### ISSUE THREAD

**Issue by durixx** [durixx/library#1]
Create new Spring Boot 3 application
-gradle project
Dependencies :

- web
- security
- jpa
- devtools
- lombok
- h2 database

Application should be runnable connected to database 
with root url '/' that will print Hello World

**Comment by serox2255** [comment]
done

**Comment by serox2255** [comment]
24.10 1h

**Comment by durixx** [comment]
code review NOT OK

**Comment by serox2255** [comment]
24.10 15m
code review fixes
